#!/usr/bin/env bash
#This script installs Nginx on an Ubuntu machine and configures it to meet the specified requirements

# Update the package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx to listen on port 80
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        return 200 "Hello World!";
    }
}
EOF

## Restart Nginx
service nginx stop
nginx -g "daemon off;"
