#!/usr/bin/env bash
#we want to add a custom Nginx response header.
# Configure Nginx to add custom HTTP response header
echo 'add_header X-Served-By $hostname;' >> /etc/nginx/nginx.conf

# Restart Nginx
service nginx restart
