#!/usr/bin/env bash

# This scripts script installs and configures HAProxy on an Ubuntu machine
# It distributes requests using a roundrobin algorithm to web-01 and web-02

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend web_frontend
    bind *:80
    mode http
    default_backend web_backend

backend web_backend
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Enable HAProxy service
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart
