#!/usr/bin/env bash
#Is the host on the network

# Check if the script was run with an argument

if [ -z "$1"]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$1"
