#!/usr/bin/env bash
#stops 4-to_infinity_and_beyond process

#get the PID of the prgram
id-$(pgrep "bash ./4-to_infinity_and_beyond" -f)

#terminate th inf process
if [ -n "$id"]
then
kill -15 "$id"
fi
