#!/usr/bin/env bash
#displays To infinity and beyond indefinitely With a sleep 2 in between each iteration I am invincible!!! when receiving a SIGTERM signal

trap 'echo "i am invincible!!!"' 15
while true;do
echo "to infinity and beyond"
sleep 2
done
