#!/usr/bin/env bash
# Edit the hosts file
sudo sed -i 's/127\.0\.0\.1\slocalhost/127.0.0.2 localhost/g' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts
sudo sh -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'
