#!/usr/bin/env bash
# Create a new hosts file

echo "127.0.0.1 localhost" > /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

# Restart networking service to apply changes
systemctl restart networking.service
