#!/usr/bin/env bash

# Update the /etc/hosts file to set localhost to 127.0.0.2
sudo sed -i 's/^127.0.0.1\s*localhost/127.0.0.1\tlocalhost\n127.0.0.2\tlocalhost/' /etc/hosts

# Update the /etc/resolv.conf file to set the DNS server for facebook.com to 8.8.8.8
echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf
